Null0: &result_dir ./results/hts_kws
Null1: &ext wav

Null2: &data_name speechcommands
Null3: &root /home/nas3/user/jeonko/spc_embedding/data
Null4: &folder SpeechCommands
Null5: &url speech_commands_v0.02

Null7: &input_dim 1
Null8: &n_classes 35

# 1. DataLoader
training_dataset_config:
  data_name: *data_name
  root: *root
  subset: 'training'
  folder_in_archive: *folder
  url: *url
  ext: *ext
train_loader_config:
  shuffle: True
validation_dataset_config:
  data_name: *data_name
  root: *root
  subset: 'validation'
  folder_in_archive: *folder
  url: *url
  ext: *ext
validation_loader_config:
  shuffle: False
test_dataset_config:
  data_name: *data_name
  root: *root
  subset: 'testing'
  folder_in_archive: *folder
  url: *url
  ext: *ext
test_loader_config:
  shuffle: False


batch_size: 128
num_workers: 4


# 2. Model
model: HTS
model_config:
  in_chans: *input_dim
  num_classes: *n_classes
  spec_size: 256
  patch_size: 4
  window_size: 8
  embed_dim: 96
  patch_stride: [4,4]
  num_heads: [4,8,16,32]
  depths: [2,2,6,2]
  expand_length: 1 # 10

  config:
    # for signal processing
    sample_rate: 16000 # 16000 for scv2, 32000 for audioset and esc-50
    clip_samples: 16000 # sample_rate * 10 # audio_set 10-sec clip
    window_size: 1024
    hop_size: 160 # 160 for scv2, 320 for audioset and esc-50
    mel_bins: 64
    fmin: 50
    fmax: 14000
    shift_max: 8000 # int(clip_samples * 0.5)

    enable_tscam: True
    enable_repeat_mode: False
    htsat_attn_heatmap: False

    loss_type: "clip_ce"

task_config:
  metric: 'acc'
  sample_input_size: 10 40 768


# 3. Optimizer
optimizer: adam
optimizer_config:
  lr: 0.0001
  weight_decay: 0.0001


# 4. LossFunction
loss: softmax


# 5. Scheduler
scheduler: steplr
scheduler_config:
  step_size: 50
  gamma: 0.9
  last_epoch: -1


# 6. Trainer
default_root_dir: *result_dir
profiler: null #advanced
max_epoch: 100
devices: -1
accelerator: gpu
num_sanity_val_steps: 2


# 7. Checkpoint
resume_checkpoint: "checkpoint/HTSAT_SCV2_Saved_1.ckpt"
checkpoint_config:
  save_top_k: 5
  monitor: "val_ACC"
  mode: "max"
  filename: "AVG-{epoch:02d}-{val_loss:.2f}-{val_ACC:02.2f}"


# 8. Random Seed
random_seed: 2301235