Null1: &ext pt

Null2: &data_name speechcommands
Null3: &root data
Null4: &folder SpeechCommands
Null5: &url speech_commands_v0.02
Null6: &feature_dim 768

# 1. DataLoader
training_dataset_config:
  data_name: *data_name
  root: *root
  subset: 'training'
  folder_in_archive: *folder
  url: *url
  ext: *ext
train_loader_config:
  shuffle: True
validation_dataset_config:
  data_name: *data_name
  root: *root
  subset: 'validation'
  folder_in_archive: *folder
  url: *url
  ext: *ext
validation_loader_config:
  shuffle: False
test_dataset_config:
  data_name: *data_name
  root: *root
  subset: 'testing'
  folder_in_archive: *folder
  url: *url
  ext: *ext
test_loader_config:
  shuffle: False


batch_size: 32
num_workers: 8


# 2. Model
model: KnowledgeDistillation
model_config:
  cumbersome_model: HTSAT
  cumbersome_config:
    input_dim: 768
    num_classes: 1211
  small_model: TCResNet
  small_config:
    input_dim: 768
    num_classes: 1211

task_config:
  metric: 'acc'
  sample_input_size: 10 40 768


# 3. Optimizer
optimizer: adam
optimizer_config:
  lr: 0.001
  weight_decay: 0.0001


# 4. LossFunction
loss: amsoftmax


# 5. Scheduler
scheduler: steplr
scheduler_config:
  step_size: 50
  gamma: 0.9
  last_epoch: -1


# 6. Trainer
default_root_dir: ./results/asv_avg_layer_12
profiler: null #advanced
max_epoch: 200
devices: -1
accelerator: cuda
num_sanity_val_steps: 2


# 7. Checkpoint
resume_checkpoint: null
checkpoint_config:
  save_top_k: 5
  monitor: "val_ACC"
  mode: "min"
  filename: "AVG-{epoch:02d}-{val_loss:.2f}-{val_ACC:02.2f}"


# 8. Random Seed
random_seed: 2301235