Null0: &result_dir ./results/hts_esc
Null1: &ext wav

Null2: &data_name esc50
Null3: &root data/esc50
Null4: &train_fold [2, 3, 4, 5]
Null5: &test_fold [1]

Null6: &input_dim 1
Null7: &n_classes 50

# 1. DataLoader
training_dataset_config:
  data_name: *data_name
  root: *root
  fold: *train_fold
train_loader_config:
  shuffle: True
validation_dataset_config:
  data_name: *data_name
  root: *root
  fold: *test_fold
validation_loader_config:
  shuffle: False
test_dataset_config:
  data_name: *data_name
  root: *root
  fold: *test_fold
test_loader_config:
  shuffle: False


batch_size: 32
num_workers: 8


# 2. Model
model: ScratchModel
model_config:
  small_model: TCResNet
  small_config:
    bins: 40
    channels: [16, 24, 32, 48]
    channel_scale: 1
    num_classes: 50
    sampling_rate: 32000

task_config:
  metric: 'acc'
  sample_input_size: 10 40 768


# 3. Optimizer
optimizer: adamw
optimizer_config:
  lr: 0.0002
  weight_decay: 0.005


# 4. LossFunction
loss: softmax


# 5. Scheduler
scheduler: steplr
scheduler_config:
  step_size: 50
  gamma: 0.9
  last_epoch: -1


# 6. Trainer
default_root_dir: ./results/tcresnet_scratch_fold1
profiler: null #advanced
max_epoch: 200
devices: -1
accelerator: cuda
num_sanity_val_steps: 2


# 7. Checkpoint
resume_checkpoint: null
checkpoint_config:
  save_top_k: 5
  monitor: "val_ACC"
  mode: "min"
  filename: "esc-{epoch:02d}-{val_loss:.2f}-{val_ACC:02.2f}"


# 8. Random Seed
random_seed: 2301235